# Generated by Django 3.1.6 on 2021-04-24 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import number.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[(None, ''), ('istek', 'İSTEK'), ('şikayet', 'ŞİKAYET')], max_length=7, null=True)),
                ('message', models.TextField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kullanıcı istek-şikayet formu',
            },
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[(None, 'Kuponu göndermek için EVET seçmelisiniz..'), ('evet', 'EVET'), ('hayır', 'HAYIR')], max_length=6, null=True)),
                ('numbers', models.CharField(default=number.models.random_int, max_length=40, null=True, verbose_name='Şanslı Numaralarınız')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Otomatik Oyna Sayısal Loto 6/49',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='GuestNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[(None, 'Kuponu göndermek için EVET seçmelisiniz..'), ('evet', 'EVET'), ('hayır', 'HAYIR')], max_length=6, null=True)),
                ('guestnumber1', models.NullBooleanField(default=False)),
                ('guestnumber2', models.NullBooleanField(default=False)),
                ('guestnumber3', models.NullBooleanField(default=False)),
                ('guestnumber4', models.NullBooleanField(default=False)),
                ('guestnumber5', models.NullBooleanField(default=False)),
                ('guestnumber6', models.NullBooleanField(default=False)),
                ('guestnumber7', models.NullBooleanField(default=False)),
                ('guestnumber8', models.NullBooleanField(default=False)),
                ('guestnumber9', models.NullBooleanField(default=False)),
                ('guestnumber10', models.NullBooleanField(default=False)),
                ('guestnumber11', models.NullBooleanField(default=False)),
                ('guestnumber12', models.NullBooleanField(default=False)),
                ('guestnumber13', models.NullBooleanField(default=False)),
                ('guestnumber14', models.NullBooleanField(default=False)),
                ('guestnumber15', models.NullBooleanField(default=False)),
                ('guestnumber16', models.NullBooleanField(default=False)),
                ('guestnumber17', models.NullBooleanField(default=False)),
                ('guestnumber18', models.NullBooleanField(default=False)),
                ('guestnumber19', models.NullBooleanField(default=False)),
                ('guestnumber20', models.NullBooleanField(default=False)),
                ('guestnumber21', models.NullBooleanField(default=False)),
                ('guestnumber22', models.NullBooleanField(default=False)),
                ('guestnumber23', models.NullBooleanField(default=False)),
                ('guestnumber24', models.NullBooleanField(default=False)),
                ('guestnumber25', models.NullBooleanField(default=False)),
                ('guestnumber26', models.NullBooleanField(default=False)),
                ('guestnumber27', models.NullBooleanField(default=False)),
                ('guestnumber28', models.NullBooleanField(default=False)),
                ('guestnumber29', models.NullBooleanField(default=False)),
                ('guestnumber30', models.NullBooleanField(default=False)),
                ('guestnumber31', models.NullBooleanField(default=False)),
                ('guestnumber32', models.NullBooleanField(default=False)),
                ('guestnumber33', models.NullBooleanField(default=False)),
                ('guestnumber34', models.NullBooleanField(default=False)),
                ('guestnumber35', models.NullBooleanField(default=False)),
                ('guestnumber36', models.NullBooleanField(default=False)),
                ('guestnumber37', models.NullBooleanField(default=False)),
                ('guestnumber38', models.NullBooleanField(default=False)),
                ('guestnumber39', models.NullBooleanField(default=False)),
                ('guestnumber40', models.NullBooleanField(default=False)),
                ('guestnumber41', models.NullBooleanField(default=False)),
                ('guestnumber42', models.NullBooleanField(default=False)),
                ('guestnumber43', models.NullBooleanField(default=False)),
                ('guestnumber44', models.NullBooleanField(default=False)),
                ('guestnumber45', models.NullBooleanField(default=False)),
                ('guestnumber46', models.NullBooleanField(default=False)),
                ('guestnumber47', models.NullBooleanField(default=False)),
                ('guestnumber48', models.NullBooleanField(default=False)),
                ('guestnumber49', models.NullBooleanField()),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kendin Oyna Sayısal Loto 6/49',
                'ordering': ['-created_date'],
            },
        ),
    ]
