# Generated by Django 3.1.6 on 2021-04-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0002_auto_20210424_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestnumber',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
