# Generated by Django 3.1.6 on 2021-04-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0003_auto_20210424_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='choice',
            field=models.CharField(choices=[(None, 'Kuponu göndermek için EVET seçmelisiniz..'), ('evet', 'EVET'), ('hayır', 'HAYIR')], max_length=6, null=True, verbose_name='Göndermek için Evet seçiniz'),
        ),
    ]
