# Generated by Django 3.1.6 on 2021-04-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0004_auto_20210426_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishrequest',
            name='message',
            field=models.TextField(null=True, verbose_name='Mesajınız'),
        ),
    ]
