# Generated by Django 3.1.6 on 2021-03-04 19:56

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LuckyCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luckynumber1', models.CharField(default=home.models.lucky, max_length=4, null=True)),
                ('luckynumber2', models.CharField(default=home.models.lucky, max_length=4, null=True)),
                ('luckynumber3', models.CharField(default=home.models.lucky, max_length=4, null=True)),
                ('luckynumber4', models.CharField(default=home.models.lucky, max_length=4, null=True)),
                ('luckynumber5', models.CharField(default=home.models.lucky, max_length=4, null=True)),
                ('luckynumber6', models.CharField(default=home.models.lucky, max_length=4, null=True)),
            ],
        ),
    ]
