# Generated by Django 3.1.6 on 2021-03-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='luckycoupon',
            options={'verbose_name_plural': 'Kazanan Kupon'},
        ),
        migrations.AddField(
            model_name='luckycoupon',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
