# Generated by Django 3.1.6 on 2021-03-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_luckycoupon_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtomaticCoupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
