# Generated by Django 3.1.6 on 2021-03-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_otomaticcoupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtomaticCoupon',
        ),
    ]
