# Generated by Django 3.1.6 on 2021-03-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='no',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='yes',
        ),
        migrations.AddField(
            model_name='vote',
            name='choice',
            field=models.CharField(choices=[('evet', 'EVET'), ('hayır', 'HAYIR')], max_length=6, null=True),
        ),
    ]
