# Generated by Django 3.1.6 on 2021-04-25 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210308_0251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
