# Generated by Django 3.1.6 on 2021-04-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_delete_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luckycoupon',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
