# Generated by Django 3.1.6 on 2021-04-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210426_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luckycoupon',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
