# Generated by Django 3.1.6 on 2021-04-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210426_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luckycoupon',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
