# Generated by Django 3.1.6 on 2021-04-25 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210426_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luckycoupon',
            name='user',
        ),
    ]
