# Generated by Django 3.1.6 on 2021-02-20 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210220_2309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
